# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6137fa391bbeb487db367e530819cbd1d09b94b8507934611cf4d6980010100384ec4ddd3087d39ae27b5adbad11441309c15d285634f296ca4d1489af8c5a74

test:
  secret_key_base: f319682aeba64ead7947d9982d855cbda202eb8d3f8d7df616b43f9a0728cfbac46b45ec6f1c3a6f67a0ed64b84f208494decb6b8241bfde2ca1476eb23d08ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
